apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: consolide
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: omarbtr/consolide-apigateway:latest
          ports:
            - containerPort: 8080
            - containerPort: 8081
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://+:8080;http://+:8081
          resources:
            requests:
              cpu: "100m"       # réserve minimale de CPU
              memory: "128Mi"   # réserve minimale de RAM
            limits:
              cpu: "500m"       # maximum CPU autorisé
              memory: "512Mi"   # maximum mémoire autorisée
