apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: consolide
data:
  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus.consolide.svc.cluster.local:9090
      isDefault: true
